### ISSUE TITLE
Tool timeouts because timeouts are too low

### ISSUE THREAD

**Issue by Dantesic** [muun/recovery#10]
Hi,

I have tried to use your official tool version but I could not get it to work.
I have then cloned your code and increased all timeouts and build executable again.

With increased timeouts tool finished correctly!

**Official version**

<img width="567" alt="image" src="https://user-images.githubusercontent.com/70580443/159933917-141a49dd-7102-45a9-99d5-3b026d211884.png">

 **My version with increased timeouts**

<img width="563" alt="image" src="https://user-images.githubusercontent.com/70580443/159934048-ac74237c-9da5-49ee-b606-03f7ebbd1dc1.png">

If you need exact values, I can make you pull request, It would be nice if you could fix this since I would like to recommend your tool to my clients.

My system is MacBook pro 2021 M1, Mac Os Monteray 12.2.1

**Comment by champo** [comment]
hi! Thanks for looking into this! How high did you have to set the timeouts? Just to be sure, you're talking about the `taskTimeout` defined in `scanner.go` right?

**Comment by Dantesic** [comment]
<img width="990" alt="image" src="https://user-images.githubusercontent.com/70580443/159953768-ef109b94-73fa-4e6e-86da-ac44676d5b34.png">
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/70580443/159953836-37e9d94b-6e22-4841-a574-3b2b3ac98581.png">
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/70580443/159954312-ec4040a7-57a5-4c48-a59c-f4e01e148a57.png">
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/70580443/159954366-6eb899d2-f5ec-4676-9c59-177edb12ec7e.png">


I'm not sure which one of these is because I did not test further, If you suspect some specific parameter, I can try and run again

**Comment by champo** [comment]
Oh you were very thorough! Given the screenshot from the time it failed, I suspect the issue lies with the one I mentioned before. If a server doesn't support batching 2 minutes might not be enough to resolve all the addresses in the task. I'll send a PR for this later today!

**Comment by champo** [comment]
Raised all the relevant timeouts [here](https://github.com/muun/recovery/commit/88270f1ab1f7a896e4a48cf5d726551d7f08ba08). Be sure to let us know if anything else pops up! Thanks

**Comment by Dantesic** [comment]
Great! Good luck with the business.
