### ISSUE TITLE
Critical! Recovery tool detect LESS money that actually i have

### ISSUE THREAD

**Issue by Fierillo** [muun/recovery#11]
Im testing the recovery tool and downloaded the 64-bit version for Windows.

I Put all the keys and the scan started. When the scan finished, i unfortunately see that the tool detected less sats that there is in my wallet.

That was disapoiting, check this please, i think is an important issue.

**Comment by champo** [comment]
Hi, we'll look into this asap. 

Can you write to support@muun.com so we can gather enough information to debug the issue? 

Thanks

**Comment by GP1992** [comment]
thanks! i did that!

**Comment by BitcoinCorp** [comment]
It the issue resolved? Or the problem persists?
