### ISSUE TITLE
Recovery tool crash when trying to scan the addresses.

### ISSUE THREAD

**Issue by GP1992** [muun/recovery#15]
OS: Windows 11
Device: Laptop ASUS VivoBook Intel i5 1135g7

Im testing the recovery tool but the program close suddenly when is trying to scan the addresses, it crash when is close to finish the scanning.

**Comment by champo** [comment]
Hi! We've just released [v2.2.3](https://github.com/muun/recovery/releases/tag/v2.2.3) which we believe should fix this issue.

**Comment by GP1992** [comment]
Thanks! unfortunately i moved all my funds to another wallet so i cant replicate the same conditions, but i tested with news funds and works properly.

**Comment by champo** [comment]
Good to know! Thanks 🙂
