### ISSUE TITLE
Display Fiat-equivalent in Invoice before user accepts

### ISSUE THREAD

**Issue by haukehess** [muun/recovery#2]
Also reported from inside the app:
After I scan an invoice-qr (or bitcoin-qr), there is only the amount in btc shown. Not in fiat. After the payment is in the history, I can open details and see the fiat amount. But by then its too late not to pay.

Would be nice to spend this line of info in the invoicing process before user accepts.

**Comment by mdb1** [comment]
Hey @haukehess, first of all thanks for the feedback!

- Regarding the issue:
You can currently visualize the amount in your primary currency by tapping on the amount in any screen before paying. 
From your comment we notice that we have a discovery problem, and will work to fix it.

- On another topic:
This repository is the one for the recovery tool. 
The repository of the iOS wallet is here: https://github.com/muun/falcon

Let us know if you have more feedback!
