### ISSUE TITLE
failed to process recovery code: invalid recovery code characters. • Update: Problem fixed thanks to Muun.

### ISSUE THREAD

**Issue by tunjis** [muun/recovery#29]
I've used the correct recovery code, yet I always get this error asking me to email  Muun. 

"Muun Recovery Tool v2.2.4

To recover your funds, you will need:

1. Your Recovery Code, which you wrote down during your security setup

2. Your Emergency Kit PDF, which you exported from the app

3. Your destination bitcoin address, where all your funds will be sent

If you have any questions, we'll be happy to answer them. Contact us at support@muun.com

Enter your Recovery Code

(it looks like this: 'ABCD-1234-POW2-R561-P120-JK26-12RW-45TT')

➜ XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX

  

Error!

The Recovery Tool encountered a problem. Please, try again.

If the problem persists, contact support@muun.com and include the file

called error_log you can find in the same folder as this tool.

――― error report ―――

failed to process recovery code: invalid recovery code characters

――――――――――――――――――――

We're always there to help.

exit status 1"

The issue was that I copied the code from a screenshot using Apple (the same as you copy the number of a credit card) but the copy wasn't accurate. Tried again with the correct code and everything works.

**Comment by champo** [comment]
hi @tunjis! Glad to hear the issue was resolved. Thanks for reaching out

**Comment by rayhan72562** [comment]
How to copy past private key.
